### ISSUE TITLE
Python import issue and shared library libtk8.6.so not found

### ISSUE THREAD

**Issue by apromix** [vincentdieltiens/homeassistant-eltako#1]
Hello Vincent!

Nice to see yours very interesting project!

I have just tried it. Unfortunately unsuccessful.

I don't know which environment do you use, but in my HA environments (HASS OS and HASS Docker container) this component doesn't work. I found 2 issues. Both occur if I try to add the `homeassistant_eltako` integration.

1. **Python import from parent directory**

Error message:
```
ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration homeassistant_eltako: No module named 'config.custom_components'
```
Import module from parent directory is not to simply ( I found [an explanation](https://codeolives.com/2020/01/10/python-reference-module-in-parent-directory/) ).
I would suggest these changes:

```
$ git status
Changes to be committed:
	deleted:    teachin/__init__.py
	renamed:    teachin/service.py -> teachinservice.py
```

```
$ git diff teachinservice.py
diff --git a/teachinservice.py b/teachinservice.py
index 5cd2c19..3349b67 100644
--- a/teachinservice.py
+++ b/teachinservice.py
@@ -1,13 +1,13 @@
 """ Teach in module for eltako devices """
 import queue
 from time import time
-from config.custom_components.homeassistant_eltako.const import (
+from .const import (
     LOGGER,
     SIGNAL_SEND_MESSAGE,
     TEACH_IN,
     TEACH_OUT,
 )
-from config.custom_components.homeassistant_eltako.utils import (
+from .utils import (
     get_communicator_reference,
     hex_list_to_str,
     str_to_hex_list,
```
2. **Error loading shared library**

Error message:
```
ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration homeassistant_eltako: Error loading shared library libtk8.6.so: No such file or directory (needed by /usr/local/lib/python3.10/lib-dynload/_tkinter.cpython-310-x86_64-linux-gnu.so)
```

In standalone container-based installation of Home Assistant Core in my both environments mentioned above is the hot fix very simply but not permanent:

```
$ docker exec -it homeassistant apk add tk
```

**Any idea why this error occurs and how fix it permanently?**

3. **After successfully configuration of the integration I found another issues:**

Integration of light device doesn't work, because the python import is unknown for me:
```
light.py:
from config.custom_components.homeassistant_enocean.light import CONF_SENDER_ID
```

Integration of cover device doesn't sent a packet. I think the content of packet is created wrong.

Error message:
```
INFO (Thread-3) [enocean.communicators.SerialCommunicator] Sending packet
DEBUG (Thread-3) [enocean.communicators.SerialCommunicator] 0x01 ['0xa5', '0x0', '0xc8', '0x2', '0xa', '0xXXXXXXXX', '0x0'] [] OrderedDict()
2022-12-15 15:27:07.307 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/enocean/communicators/serialcommunicator.py", line 29, in run
    self.__ser.write(bytearray(packet.build()))
ValueError: byte must be in range(0, 256)

```
I think the "byte" `'0xXXXXXXXX'` should be `'0xXX','0xXX','0xXX','0xXX'`

**What do you mean about this?**

Many Thanks.

**Comment by vincentdieltiens** [comment]
Hi @apromix ,

Sorry, I did not receive email notification for your message.

> I don't know which environment do you use, but in my HA environments (HASS OS and HASS Docker container) this component doesn't work. 

HASS OS (2023.4.6) is directly installed on a Rpi 3+ (https://www.home-assistant.io/installation/raspberrypi/)

```
homeassistant_eltako git:(master) ✗ python --version
Python 3.9.2
```

> 1. Python import from parent directory

Maybe check the last update I just pushed. I changed it some time ago for : 

```python
from ..const import (
    LOGGER,
    SIGNAL_SEND_MESSAGE,
    TEACH_IN,
    TEACH_OUT
)
from ..utils import (
    get_communicator_reference,
    hex_list_to_str,
    str_to_hex_list,
)
```

> 2. Error loading shared library

Mmmmmh, Surprising, I seems that I don't have tk installed : 
```
➜  homeassistant_eltako git:(master) ✗ apt list --installed            
Listing... Done
ack/now 3.4.0-1 all [installed,local]
adduser/now 3.118 all [installed,local]
apt/now 2.2.4 arm64 [installed,local]
base-files/now 11.1+deb11u6 arm64 [installed,local]
base-passwd/now 3.5.51 arm64 [installed,local]
bash/now 5.1-2+deb11u1 arm64 [installed,local]
bsdutils/now 1:2.36.1-8+deb11u1 arm64 [installed,local]
ca-certificates/now 20210119 all [installed,local]
colordiff/now 1.0.18-1.1 all [installed,local]
coreutils/now 8.32-4 arm64 [installed,local]
curl/now 7.74.0-1.3+deb11u7 arm64 [installed,local]
dash/now 0.5.11+git20200708+dd9ef66-5 arm64 [installed,local]
debconf/now 1.5.77 all [installed,local]
debian-archive-keyring/now 2021.1.1 all [installed,local]
debianutils/now 4.11.2 arm64 [installed,local]
diffutils/now 1:3.7-5 arm64 [installed,local]
dpkg/now 1.20.12 arm64 [installed,local]
e2fsprogs/now 1.46.2-2 arm64 [installed,local]
findutils/now 4.8.0-1 arm64 [installed,local]
gcc-10-base/now 10.2.1-6 arm64 [installed,local]
gcc-9-base/now 9.3.0-22 arm64 [installed,local]
git-man/now 1:2.30.2-1+deb11u2 all [installed,local]
git/now 1:2.30.2-1+deb11u2 arm64 [installed,local]
gpgv/now 2.2.27-2+deb11u2 arm64 [installed,local]
grep/now 3.6-1 arm64 [installed,local]
gzip/now 1.10-4+deb11u1 arm64 [installed,local]
hostname/now 3.23 arm64 [installed,local]
init-system-helpers/now 1.60 all [installed,local]
iputils-ping/now 3:20210202-1 arm64 [installed,local]
jq/now 1.6-2.1 arm64 [installed,local]
less/now 551-2 arm64 [installed,local]
libacl1/now 2.2.53-10 arm64 [installed,local]
libapt-pkg6.0/now 2.2.4 arm64 [installed,local]
libarchive-tools/now 3.4.3-2+deb11u1 arm64 [installed,local]
libarchive13/now 3.4.3-2+deb11u1 arm64 [installed,local]
libattr1/now 1:2.4.48-6 arm64 [installed,local]
libaudit-common/now 1:3.0-2 all [installed,local]
libaudit1/now 1:3.0-2 arm64 [installed,local]
libblas3/now 3.9.0-3 arm64 [installed,local]
libblkid1/now 2.36.1-8+deb11u1 arm64 [installed,local]
libbrotli1/now 1.0.9-2+b2 arm64 [installed,local]
libbsd0/now 0.11.3-1 arm64 [installed,local]
libbz2-1.0/now 1.0.8-4 arm64 [installed,local]
libc-bin/now 2.31-13+deb11u5 arm64 [installed,local]
libc-l10n/now 2.31-13+deb11u5 all [installed,local]
libc6/now 2.31-13+deb11u5 arm64 [installed,local]
libcap-ng0/now 0.7.9-2.2+b1 arm64 [installed,local]
libcap2-bin/now 1:2.44-1 arm64 [installed,local]
libcap2/now 1:2.44-1 arm64 [installed,local]
libcbor0/now 0.5.0+dfsg-2 arm64 [installed,local]
libcjson1/now 1.7.14-1 arm64 [installed,local]
libcom-err2/now 1.46.2-2 arm64 [installed,local]
libconfig-inifiles-perl/now 3.000003-1 all [installed,local]
libcrypt1/now 1:4.4.18-4 arm64 [installed,local]
libcurl3-gnutls/now 7.74.0-1.3+deb11u7 arm64 [installed,local]
libcurl4/now 7.74.0-1.3+deb11u7 arm64 [installed,local]
libdb5.3/now 5.3.28+dfsg1-0.8 arm64 [installed,local]
libdbus-1-3/now 1.12.24-0+deb11u1 arm64 [installed,local]
libdebconfclient0/now 0.260 arm64 [installed,local]
libedit2/now 3.1-20191231-2+b1 arm64 [installed,local]
liberror-perl/now 0.17029-1 all [installed,local]
libexpat1/now 2.2.10-2+deb11u5 arm64 [installed,local]
libext2fs2/now 1.46.2-2 arm64 [installed,local]
libffi7/now 3.3-6 arm64 [installed,local]
libfido2-1/now 1.6.0-2 arm64 [installed,local]
libfile-next-perl/now 1.18-1 all [installed,local]
libgcc-s1/now 10.2.1-6 arm64 [installed,local]
libgcrypt20/now 1.8.7-6 arm64 [installed,local]
libgdbm-compat4/now 1.19-2 arm64 [installed,local]
libgdbm6/now 1.19-2 arm64 [installed,local]
libgmp10/now 2:6.2.1+dfsg-1+deb11u1 arm64 [installed,local]
libgnutls30/now 3.7.1-5+deb11u3 arm64 [installed,local]
libgpg-error0/now 1.38-2 arm64 [installed,local]
libgssapi-krb5-2/now 1.18.3-6+deb11u3 arm64 [installed,local]
libhogweed6/now 3.7.3-1 arm64 [installed,local]
libicu67/now 67.1-7 arm64 [installed,local]
libidn2-0/now 2.3.0-5 arm64 [installed,local]
libjq1/now 1.6-2.1 arm64 [installed,local]
libk5crypto3/now 1.18.3-6+deb11u3 arm64 [installed,local]
libkeyutils1/now 1.6.1-2 arm64 [installed,local]
libkrb5-3/now 1.18.3-6+deb11u3 arm64 [installed,local]
libkrb5support0/now 1.18.3-6+deb11u3 arm64 [installed,local]
libldap-2.4-2/now 2.4.57+dfsg-3+deb11u1 arm64 [installed,local]
liblinear4/now 2.3.0+dfsg-5 arm64 [installed,local]
liblua5.3-0/now 5.3.3-1.1+b1 arm64 [installed,local]
liblz4-1/now 1.9.3-2 arm64 [installed,local]
liblzma5/now 5.2.5-2.1~deb11u1 arm64 [installed,local]
libmariadb3/now 1:10.5.18-0+deb11u1 arm64 [installed,local]
libmd0/now 1.0.3-3 arm64 [installed,local]
libmosquitto1/now 2.0.11-1 arm64 [installed,local]
libmount1/now 2.36.1-8+deb11u1 arm64 [installed,local]
libmpdec3/now 2.5.1-1 arm64 [installed,local]
libncurses6/now 6.2+20201114-2 arm64 [installed,local]
libncursesw6/now 6.2+20201114-2 arm64 [installed,local]
libnettle8/now 3.7.3-1 arm64 [installed,local]
libnghttp2-14/now 1.43.0-1 arm64 [installed,local]
libnsl2/now 1.3.0-2 arm64 [installed,local]
libonig5/now 6.9.6-1.1 arm64 [installed,local]
libp11-kit0/now 0.23.22-1 arm64 [installed,local]
libpam-modules-bin/now 1.4.0-9+deb11u1 arm64 [installed,local]
libpam-modules/now 1.4.0-9+deb11u1 arm64 [installed,local]
libpam-runtime/now 1.4.0-9+deb11u1 all [installed,local]
libpam0g/now 1.4.0-9+deb11u1 arm64 [installed,local]
libpcap0.8/now 1.10.0-2 arm64 [installed,local]
libpcre2-8-0/now 10.36-2+deb11u1 arm64 [installed,local]
libpcre3/now 2:8.39-13 arm64 [installed,local]
libperl5.32/now 5.32.1-4+deb11u2 arm64 [installed,local]
libpsl5/now 0.21.0-1.2 arm64 [installed,local]
libpython3-stdlib/now 3.9.2-3 arm64 [installed,local]
libpython3.9-minimal/now 3.9.2-1 arm64 [installed,local]
libpython3.9-stdlib/now 3.9.2-1 arm64 [installed,local]
libreadline8/now 8.1-1 arm64 [installed,local]
librtmp1/now 2.4+20151223.gitfa8646d.1-2+b2 arm64 [installed,local]
libsasl2-2/now 2.1.27+dfsg-2.1+deb11u1 arm64 [installed,local]
libsasl2-modules-db/now 2.1.27+dfsg-2.1+deb11u1 arm64 [installed,local]
libseccomp2/now 2.5.1-1+deb11u1 arm64 [installed,local]
libselinux1/now 3.1-3 arm64 [installed,local]
libsemanage-common/now 3.1-1 all [installed,local]
libsemanage1/now 3.1-1+b2 arm64 [installed,local]
libsepol1/now 3.1-1 arm64 [installed,local]
libsmartcols1/now 2.36.1-8+deb11u1 arm64 [installed,local]
libsqlite3-0/now 3.34.1-3 arm64 [installed,local]
libss2/now 1.46.2-2 arm64 [installed,local]
libssh2-1/now 1.9.0-2 arm64 [installed,local]
libssl1.1/now 1.1.1n-0+deb11u4 arm64 [installed,local]
libstdc++6/now 10.2.1-6 arm64 [installed,local]
libsystemd0/now 247.3-7+deb11u1 arm64 [installed,local]
libtasn1-6/now 4.16.0-2+deb11u1 arm64 [installed,local]
libtinfo6/now 6.2+20201114-2 arm64 [installed,local]
libtirpc-common/now 1.3.1-1+deb11u1 all [installed,local]
libtirpc3/now 1.3.1-1+deb11u1 arm64 [installed,local]
libudev1/now 247.3-7+deb11u1 arm64 [installed,local]
libunistring2/now 0.9.10-4 arm64 [installed,local]
libuuid1/now 2.36.1-8+deb11u1 arm64 [installed,local]
libxml2/now 2.9.10+dfsg-6.7+deb11u4 arm64 [installed,local]
libxxhash0/now 0.8.0-2 arm64 [installed,local]
libzstd1/now 1.4.8+dfsg-2.1 arm64 [installed,local]
locales/now 2.31-13+deb11u5 all [installed,local]
login/now 1:4.8.1-1 arm64 [installed,local]
logsave/now 1.46.2-2 arm64 [installed,local]
lsb-base/now 11.1.0 all [installed,local]
lua-lpeg/now 1.0.2-1 arm64 [installed,local]
mariadb-client-10.5/now 1:10.5.18-0+deb11u1 arm64 [installed,local]
mariadb-client-core-10.5/now 1:10.5.18-0+deb11u1 arm64 [installed,local]
mariadb-client/now 1:10.5.18-0+deb11u1 all [installed,local]
mariadb-common/now 1:10.5.18-0+deb11u1 all [installed,local]
mawk/now 1.3.4.20200120-2 arm64 [installed,local]
media-types/now 4.0.0 all [installed,local]
mosquitto-clients/now 2.0.11-1 arm64 [installed,local]
mount/now 2.36.1-8+deb11u1 arm64 [installed,local]
mysql-common/now 5.8+1.0.7 all [installed,local]
ncurses-base/now 6.2+20201114-2 all [installed,local]
ncurses-bin/now 6.2+20201114-2 arm64 [installed,local]
net-tools/now 1.60+git20181103.0eebece-1 arm64 [installed,local]
nmap-common/now 7.91+dfsg1+really7.80+dfsg1-2 all [installed,local]
nmap/now 7.91+dfsg1+really7.80+dfsg1-2 arm64 [installed,local]
openssh-client/now 1:8.4p1-5+deb11u1 arm64 [installed,local]
openssl/now 1.1.1n-0+deb11u4 arm64 [installed,local]
passwd/now 1:4.8.1-1 arm64 [installed,local]
patch/now 2.7.6-7 arm64 [installed,local]
perl-base/now 5.32.1-4+deb11u2 arm64 [installed,local]
perl-modules-5.32/now 5.32.1-4+deb11u2 all [installed,local]
perl/now 5.32.1-4+deb11u2 arm64 [installed,local]
python3-minimal/now 3.9.2-3 arm64 [installed,local]
python3.9-minimal/now 3.9.2-1 arm64 [installed,local]
python3.9/now 3.9.2-1 arm64 [installed,local]
python3/now 3.9.2-3 arm64 [installed,local]
readline-common/now 8.1-1 all [installed,local]
sed/now 4.7-1 arm64 [installed,local]
sysvinit-utils/now 2.96-7+deb11u1 arm64 [installed,local]
tar/now 1.34+dfsg-1 arm64 [installed,local]
tzdata/now 2021a-1+deb11u9 all [installed,local]
unzip/now 6.0-26+deb11u1 arm64 [installed,local]
util-linux/now 2.36.1-8+deb11u1 arm64 [installed,local]
wget/now 1.21-1+deb11u1 arm64 [installed,local]
zip/now 3.0-12 arm64 [installed,local]
zlib1g/now 1:1.2.11.dfsg-2+deb11u2 arm64 [installed,local]
zsh-common/now 5.8-6+deb11u1 all [installed,local]
zsh/now 5.8-6+deb11u1 arm64 [installed,local]
```

> 3. After successfully configuration of the integration I found another issues:

The version of homeassistant_eltako on the github was relying on other module I found named `homeassistant_enocean` which was a fork of the original `enocean` component (https://github.com/home-assistant/core/tree/dev/homeassistant/components/enocean)

In the update I pushed today, I don't rely anymore on that component.

**Comment by apromix** [comment]
Hello @vincentdieltiens !

The last commited version works better. Some errors from homeassistant.helpers.integration_platform but maybe not critical.
I added the component into HA successfully.


**UPDATE**:

I can acknowledge that devices

- F4SR14 (Simple Light) + FL62 + FR62
- FUD14 (Dimmer)
- FSB14 (Cover)

are working for me.


Many thanks ..

**Comment by vincentdieltiens** [comment]
Good news :)

Don't hesitate if you find bugs or if you want to submit PRs :)

This is far from perfect but not easy because Eltako does not follow exactly EnOcean protocol :(

Vincent
